### ISSUE TITLE
Node.js Package

### ISSUE THREAD

**Issue by uipoet** [mmonteleone/pavlov#14]
Palov is super awesome for testing our jQuery plugin: http://ninjaui.com

Would you mind distributing via NPM? Should be straight forward, considering qunit is already available to use as a dependency through NPM.

We seek a Node.js package so we can automate our tests through a Jakefile and depend on the correct versions without having to maintain a copy in our own repo.

**Comment by uipoet** [comment]
Also looking to have pavlov available for command line execution via Node.js to run automated tests without a browser as part of our build script.

**Comment by bsbodden** [comment]
That would be very nice for adoption of this library. Copying JS files into a directory is so 2010! :-)
