### ISSUE TITLE
Update to QUnit 1.7.0pre

### ISSUE THREAD

**Issue by brianmhunt** [mmonteleone/pavlov#17]
Does Pavlov work with [QUnit 1.7.0pre](https://github.com/jquery/qunit/blob/master/qunit/qunit.js)?

It would be good to have the QUnit library included with Pavlov updated to the latest QUnit.

**Comment by mmonteleone** [comment]
Thanks.  With the final tagging of 0.3.0, pavlov now included 1.9.0pre by default.
