### ISSUE TITLE
Can't use wait() more than once?

### ISSUE THREAD

**Issue by eykd** [mmonteleone/pavlov#2]
Perhaps I don't quite understand how wait() (or the underlying start()/stop() engine), but I can't seem to get wait() to work more than once in a particular it() block. Any tests inside the function body of subsequent wait() calls are ignored (though the code does run).

**Comment by eykd** [comment]
Now I'm having trouble reproduce this in simple test code. I'll keep trying, and post a reproduction as soon as I can. :/

**Comment by mmonteleone** [comment]
Hi eykd.  I'm cleaning up pavlov's issues.  Were you ever able to reproduce this?

**Comment by eykd** [comment]
No, sorry, I've moved on to other projects.

**Comment by mmonteleone** [comment]
Ok, thank you!
