### ISSUE TITLE
cli for pavlov?

### ISSUE THREAD

**Issue by gregglind** [mmonteleone/pavlov#3]
I know the 'cli for qunit' issue is quite muddled already, but a 'blessed' solution would be nice, especially incorporating pavlov.

**Comment by mmonteleone** [comment]
I agree that tooling such as a cli is useful.  However, the scope of pavlov is just to be a set of API extensions for QUnit test suites (and therefore making use of any of QUnit's existing first-party and third-party tooling ecosystem)  As such, there are no current plans for pavlov to implement its own cli tools.  This also aligns with pavlov's roadmap to become test-framework agnostic, so even QUnit will just be one option for pavlov-based tests.
